# application properties
service:
  name: ${spring.application.name}
  version: 1.0.0
spring.application.name: api_management
server:
  port: 7002
  servlet:
    context-path: /api-management

spring.profiles.active: local # override active profile by passing command-line argument --spring.profiles.active = {env}
twc.service.name: 'api-management'

# database
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://twnext-sbpostgres-ci.postgres.database.azure.com:5432/trackwizz_connect_test
    username: tssadmin
    password: TrackWizz@2023@#
  jpa:
    hibernate:
      ddl-auto: update # create/update | change it to 'update' once db schema confirmed

# swagger
spring-doc:
  swagger-ui:
    path: /swagger

twc:
  jwt:
    token:
      expiry: 60  # 60 * 24 * 365 | 1 year = minutes * hours * days
