# application properties
service:
  name: ${spring.application.name}
  version: 1.0.0
spring.application.name: face_match
server:
  port: 7004
  servlet:
    context-path: /face-match

spring.profiles.active: local # override active profile by passing command-line argument --spring.profiles.active = {env}
twc.service.name: 'face-match'

# database
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://twnext-sbpostgres-ci.postgres.database.azure.com:5432/trackwizz_connect_test
    username: tssadmin
    password: TrackWizz@2023@#
  jpa:
    hibernate:
      ddl-auto: update # create/update | change it to 'update' once db schema confirmed

# swagger
spring-doc:
  swagger-ui:
    path: /swagger

# external services
# ORBO
photomatch.orbo.base-url: http://20.219.215.248
#externalservice.orbo.base-url: http://20.197.13.41:9001
photomatch.orbo.endpoint: /match

#twc.jwt.excluded-urls: /swagger-ui/**,/swagger,/v3/api-docs/**
twc.jwt.token.expiry: 60  # 60 * 24 * 365 | 1 year = minutes * hours * days

spring.codec.max-in-memory-size: 20MB # TODO review size (20MB) default is 256KB DataBufferLimitException

