name: Build and Push Docker Image

on:
  workflow_call:
    inputs:
      service_name:
        description: 'Name of the service to build and push'
        type: string
        required: true
      version:
        description: 'Version of the image to tag and push'
        type: string
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: |
          cd "${{ github.workspace }}/services/${{ inputs.service_name }}"
          docker build -t trackwizz/${{ inputs.service_name }}:${{ inputs.version }} .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push Docker Image
        run: |
          cd "${{ github.workspace }}/services/${{ inputs.service_name }}"
          docker push trackwizz/${{ inputs.service_name }}:${{ inputs.version }} || exit 1
